version: "3.7"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./packages/api
      target: development
    volumes:
      - ./packages/api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - db


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: localdev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
