name: Lint PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            perf
            revert
            deps
            docs
            refactor
            test
            chore
          scopes: |
            repo
            account
            arcade
            articles
            auth
            blog
            campaign
            chat
            community
            dashboard
            design-analysis
            design-system
            designer-ext
            designer-hud
            designer-state
            designer-tools
            discussion
            guidance
            help
            i18n
            integrations
            lab
            library
            licensing
            marketing
            messaging
            moderation
            navigation
            notebooks
            puzzles
            rewards
            rna-metrics
            rna-vis
            tools
          requireScope: true
